export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    width: "180px",
    cursor: "pointer",
    transition: "0.5s",
    marginTop: "20px",
    marginRight: "20px",
    marginLeft: "20px",
  },
  relativeCard: { position: "relative" },
  CardImg: {
    width: "180px",
    borderRadius: "8px",
    transition: "0.2s",
    boxShadow: "0.2px 3px 30px #00000044",
    border: "2px solid transparent",
  },
  CardImg_hover: {
    transitionDelay: "1s",
    border: "2px solid #ebb928",
    transform: "scale(1.5)",
    position: "relative",
    zIndex: "100",
  },
  textCategory: {
    margin: "0px",
    padding: "0px",
    fontSize: "10px",
    fontWeight: "500",
    color: "#1da190",
    letterSpacing: "0.25",
  },
  titleInformation: { marginTop: "15px", marginLeft: "4px" },
  title: {
    margin: "0px",
    padding: "0px",
    color: "rgba(255, 255, 255, 0.85)",
    fontSize: "14px",
    marginTop: "5px",
  },
  starCount: {
    backgroundColor: "#ebb928",
    boxShadow: "0.2px 1.5px 15px #ebba287e",
    width: "30px",
    height: "15px",
    color: "rgb(92, 92, 92)",
    fontSize: "12px",
    borderRadius: "20px",
    textAlign: "center",
    position: "absolute",
    bottom: "0px",
    right: "-10px",
  },
  heart: {
    color: "red",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: "150",
  },
  heartIcon: {
    transform: "scale(4)",
    opacity: "0",
  },
  heartCount: {
    color: "red",
    position: "absolute",
    top: "-5px",
    transform: "scale(1.2)",
  },
};
